[package]
name = "bd-sdr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crossbeam.workspace = true
log.workspace = true

[build-dependencies]
cc = "1"

[features]
default = ["usrp"]
hackrf = []
bladerf = []
usrp = []
soapysdr = []
